name: pre-commit GitHub Action
description: Installs pre-commit hooks with cache and runs them
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: pre-commit/action@v3.0.0

branding:
  icon: 'check-square'
  color: 'green'
